/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dictionarymodel.DictionaryEntry;
import java.util.function.Consumer;

/**
 *
 * @author eco
 */
public class DefinitionPanel extends javax.swing.JPanel {

	/**
	 * Creates new form DefinitionPanel
	 */
	public DefinitionPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                homeButton = new javax.swing.JButton();
                definitionPanel = new view.DictionaryEntryPanel();
                nextPanel = new view.DefinitionNextPanel();
                prevPanel = new view.DefinitionPreviousPanel();

                setBackground(new java.awt.Color(255, 255, 255));

                homeButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
                homeButton.setForeground(new java.awt.Color(65, 114, 159));
                homeButton.setText("< Back to home");
                homeButton.setBorder(null);
                homeButton.setBorderPainted(false);
                homeButton.setContentAreaFilled(false);

                nextPanel.setBackground(new java.awt.Color(255, 255, 255));

                prevPanel.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(homeButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(definitionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(prevPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(homeButton)
                                .addGap(16, 16, 16)
                                .addComponent(definitionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(prevPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

	public void setData(DictionaryEntry entry) {
		definitionPanel.setData(entry);
		nextPanel.setData(entry.next);
		prevPanel.setData(entry.prev);
	}

	public void addGotoHomeListener(Runnable listener) {
		homeButton.addActionListener((ae) -> {
			listener.run();
		});
	}

	public void addGotoDefinitionListener(Consumer<DictionaryEntry> listener) {
		nextPanel.addGotoDefinitionListener(listener);
		prevPanel.addGotoDefinitionListener(listener);
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private view.DictionaryEntryPanel definitionPanel;
        private javax.swing.JButton homeButton;
        private view.DefinitionNextPanel nextPanel;
        private view.DefinitionPreviousPanel prevPanel;
        // End of variables declaration//GEN-END:variables
}
