/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import dictionarymodel.DictionaryModel;

/**
 *
 * @author eco
 */
public class DictionaryAppFrame extends javax.swing.JFrame {


	/**
	 * Creates new form DictionaryAppFrame
	 */
	public DictionaryAppFrame() {
		initComponents();

		CardLayout cards = (CardLayout) mainPanel.getLayout();
		DictionaryModel dictionary = new DictionaryModel();
		

		footerPanel.addAboutListener(() -> {
			new AboutDialog(this, true)
				.setVisible(true);
		});
		footerPanel.addTermsAndConditionListener(() -> {
			new TermsAndConditionDialog(this, true)
				.setVisible(true);
		});

	}


	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                headerPanel = new view.HeaderPanel();
                footerPanel = new view.FooterPanel();
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
                javax.swing.JPanel panel = new javax.swing.JPanel();
                mainPanel = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("JJSA-Webster Dictionary");
                setMinimumSize(new java.awt.Dimension(640, 112));

                headerPanel.setPreferredSize(new java.awt.Dimension(536, 56));
                getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

                footerPanel.setPreferredSize(new java.awt.Dimension(269, 56));
                getContentPane().add(footerPanel, java.awt.BorderLayout.PAGE_END);

                scrollPane.setBackground(new java.awt.Color(255, 255, 255));
                scrollPane.setBorder(null);
                scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

                panel.setBackground(new java.awt.Color(255, 255, 255));

                mainPanel.setBackground(new java.awt.Color(255, 0, 0));
                mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                mainPanel.setMaximumSize(new java.awt.Dimension(640, 32767));
                mainPanel.setMinimumSize(new java.awt.Dimension(640, 0));
                mainPanel.setLayout(new java.awt.CardLayout());

                javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
                panel.setLayout(panelLayout);
                panelLayout.setHorizontalGroup(
                        panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                panelLayout.setVerticalGroup(
                        panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                scrollPane.setViewportView(panel);

                getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DictionaryAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DictionaryAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DictionaryAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DictionaryAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DictionaryAppFrame().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private view.FooterPanel footerPanel;
        private view.HeaderPanel headerPanel;
        private javax.swing.JPanel mainPanel;
        // End of variables declaration//GEN-END:variables

}
