/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.ListCellRenderer;
import dictionarymodel.DictionarySingleEntry;
import java.awt.Component;
import javax.swing.JList;

/**
 *
 * @author eco
 */
public class DictionarySingleEntryPanel extends javax.swing.JPanel implements ListCellRenderer<DictionarySingleEntry> {

	/**
	 * Creates new form DictionarySingleEntryPanel
	 */
	public DictionarySingleEntryPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 422, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents

	@Override
	public Component getListCellRendererComponent(JList<? extends DictionarySingleEntry> jlist, DictionarySingleEntry e, int i, boolean bln, boolean bln1) {
		setData(e);
		return this;
	}

	public void setData(DictionarySingleEntry dictionarySingleEntry) {
		// TODO implement setdata
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
}
