/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.AbstractListModel;
import dictionarymodel.PartsOfSpeech;
import dictionarymodel.DictionaryEntry;
import dictionarymodel.DictionarySingleEntry;

/**
 *
 * @author eco
 */
public class DictionaryEntryPanel extends javax.swing.JPanel {

	/**
	 * Creates new form DictionaryEntryPanel
	 */
	public DictionaryEntryPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                wordLabel = new javax.swing.JLabel();
                definitionsList = new javax.swing.JList<>();

                setBackground(new java.awt.Color(255, 255, 255));

                wordLabel.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
                wordLabel.setText("Lorem");

                definitionsList.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
                definitionsList.setAutoscrolls(false);
                definitionsList.setCellRenderer(new DictionarySingleEntryPanel());
                definitionsList.setOpaque(false);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(wordLabel)
                                .addContainerGap(410, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(definitionsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(wordLabel)
                                .addGap(16, 16, 16)
                                .addComponent(definitionsList)
                                .addGap(0, 0, 0))
                );
        }// </editor-fold>//GEN-END:initComponents

	public void setData(DictionaryEntry dictionaryEntry) {
		wordLabel.setText(dictionaryEntry.word);
		definitionsList.setModel(new AbstractListModel() {
			DictionarySingleEntry[] definitions = dictionaryEntry.entries
				.values()
				.toArray(new DictionarySingleEntry[0]);

			@Override
			public int getSize() {
				return definitions.length;
			}

			@Override
			public Object getElementAt(int i) {
				return definitions[i];
			}

		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JList<DictionarySingleEntry> definitionsList;
        private javax.swing.JLabel wordLabel;
        // End of variables declaration//GEN-END:variables
}
