/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import dictionarymodel.*;

/**
 *
 * @author eco
 */
public class DictionaryAppFrame extends javax.swing.JFrame {
	private final DictionaryModel dictionary;

	/**
	 * Creates new form DictionaryAppFrame
	 */
	public DictionaryAppFrame() {
		initComponents();

		dictionary = new DictionaryModel();
		
		headerPanel.addGotoHomeListener(this::gotoHome);
		headerPanel.addSearchListener(this::search);

		footerPanel.addAboutListener(() -> {
			new AboutDialog(this, true)
				.setVisible(true);
		});
		footerPanel.addTermsAndConditionListener(() -> {
			new TermsAndConditionDialog(this, true)
				.setVisible(true);
		});

		mainPanel.setModel(dictionary);
		mainPanel.addGotoDefinitionListener(this::gotoDefinition);

		searchPanel.addGotoDefintionListener(this::gotoDefinition);

		definitionPanel.addGotoHomeListener(this::gotoHome);
		definitionPanel.addGotoDefinitionListener(this::gotoDefinition);

		switchCard("main");
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                headerPanel = new view.HeaderPanel();
                footerPanel = new view.FooterPanel();
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
                javax.swing.JPanel panel = new javax.swing.JPanel();
                contentPanel = new javax.swing.JPanel();
                mainPanel = new view.MainPanel();
                definitionPanel = new view.DefinitionPanel();
                searchPanel = new view.SearchPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("JJSA-Webster Dictionary");
                setMinimumSize(new java.awt.Dimension(672, 112));

                headerPanel.setPreferredSize(new java.awt.Dimension(536, 56));
                getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

                footerPanel.setPreferredSize(new java.awt.Dimension(269, 56));
                getContentPane().add(footerPanel, java.awt.BorderLayout.PAGE_END);

                scrollPane.setBackground(new java.awt.Color(255, 255, 255));
                scrollPane.setBorder(null);
                scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                scrollPane.setToolTipText("");

                panel.setBackground(new java.awt.Color(255, 255, 255));

                contentPanel.setBackground(new java.awt.Color(255, 255, 255));
                contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                contentPanel.setMaximumSize(new java.awt.Dimension(640, 32767));
                contentPanel.setMinimumSize(new java.awt.Dimension(640, 0));
                contentPanel.setLayout(new java.awt.CardLayout());
                contentPanel.add(mainPanel, "main");
                contentPanel.add(definitionPanel, "definition");

                searchPanel.setBackground(new java.awt.Color(255, 255, 255));
                contentPanel.add(searchPanel, "search");

                javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
                panel.setLayout(panelLayout);
                panelLayout.setHorizontalGroup(
                        panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                panelLayout.setVerticalGroup(
                        panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                scrollPane.setViewportView(panel);

                getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DictionaryAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DictionaryAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DictionaryAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DictionaryAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DictionaryAppFrame().setVisible(true);
			}
		});
	}

	private void switchCard(String name) {
		var cards = (CardLayout) contentPanel.getLayout();
		cards.show(contentPanel,name);
	}

	private void gotoDefinition(DictionaryEntry entry) {
		definitionPanel.setData(entry);
		switchCard("definition");
		searchPanel.clear();
	}

	private void gotoHome() {
		mainPanel.refresh();
		switchCard("main");
		searchPanel.clear();
	}

	private void search(String query) {
		var result = dictionary.search(query);
		searchPanel.setData(query, result);
		switchCard("search");
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel contentPanel;
        private view.DefinitionPanel definitionPanel;
        private view.FooterPanel footerPanel;
        private view.HeaderPanel headerPanel;
        private view.MainPanel mainPanel;
        private view.SearchPanel searchPanel;
        // End of variables declaration//GEN-END:variables
}
