/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dictionarymodel.DictionaryEntry;

/**
 *
 * @author eco
 */
public class SuggestionPanel extends javax.swing.JPanel {

	/**
	 * Creates new form SuggestionPanel
	 */
	public SuggestionPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                leftLabel = new javax.swing.JLabel();
                buttonLabel = new javax.swing.JLabel();
                rightLabel = new javax.swing.JLabel();

                setOpaque(false);

                leftLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/left.png"))); // NOI18N

                buttonLabel.setBackground(new java.awt.Color(39, 68, 114));
                buttonLabel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
                buttonLabel.setForeground(new java.awt.Color(255, 255, 255));
                buttonLabel.setText("jLabel1");
                buttonLabel.setOpaque(true);

                rightLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/right.png"))); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(leftLabel)
                                .addGap(0, 0, 0)
                                .addComponent(buttonLabel)
                                .addGap(0, 0, 0)
                                .addComponent(rightLabel)
                                .addContainerGap(16, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(buttonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(leftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(8, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

	public void setData(DictionaryEntry entry) {
		buttonLabel.setText(entry.word);
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel buttonLabel;
        private javax.swing.JLabel leftLabel;
        private javax.swing.JLabel rightLabel;
        // End of variables declaration//GEN-END:variables
}
